### ISSUE TITLE
[Request] npcap

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Nonportable#15]
### Criteria

For a package to be acceptable in the Nonportable bucket, it should be:

- [x] a reasonably well-known and widely used application
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version

### Information

**Name:** [name of new package] 
npcap

**Description:** [clear and concise details of what it is]
Npcap is a packet capture and injection library for Windows by the Nmap Project

**Homepage:** [a URL/link]
https://github.com/nmap

**Download link(s):** [URL(s)/link(s)]
https://npcap.com/dist/npcap-1.70.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/nmap/npcap
https://wiki.wireshark.org/Npcap
https://alternativeto.net/software/npcap/about/
https://www.saashub.com/compare-winpcap-vs-npcap

**Comment by issaclin32** [comment]
Unfortunately **npcap** [only allows silent install for the OEM version](https://npcap.com/guide/npcap-users-guide.html#:~:text=Installs%20Npcap%20without%20showing%20any,available%20only%20for%20Npcap%20OEM.&text=The%20default%20for%20this%20option%20is%20yes%20%2C%20so%20the%20installer,installation%20independent%20from%20this%20option.) (requires **commercial license**).

It is possible to reverse-engineer the installer, and install the drivers/DLLs in `installer.script`, but that would be **prone to errors** due to future updates. (For example, if they add extra components, the old script will not work)

**Comment by scillidan** [comment]
I asked AI, and it seems that due to the issues with hardcoded settings and the need to install driver files, it suggested that I choose one of two options:

- Install it manually but use `scoop` to manage updates and uninstallations
- Extract the `.exe` to obtain some DLLs.

I think the first option is better.
