### ISSUE TITLE
office-365-apps-np@23.4.0: hash check failed

### ISSUE THREAD

**Issue by pisarz77** [ScoopInstaller/Nonportable#377]
#### Scoop Configuration

Im testing scoop and did office365 with this result

Installing 'office-365-apps-np' (23.4.0) [64bit] from 'nonportable' bucket
dl.7z_ (185.5 KB) [===========================================================================================] 100%
Checking hash of dl.7z_ ... ERROR Hash check failed!
App:         nonportable/office-365-apps-np
URL:         https://download.microsoft.com/download/#/dl.7z_
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    567de460896d131dd5e0710540e270010158ef6cd88b4974ca2c9bdb7f64b1f4
Actual:      f35680924c9dd19cc653c3b16ef10dbd98d0bcfc303a120f9300eec3a96342fb

**Comment by jclinton-ibboost** [comment]
Hi, even with the updated hash it seems like the download URL isn't correct as it is downloading the Microsoft Download landing page rather than the office package.

In this commit https://github.com/ScoopInstaller/Nonportable/commit/f445667c20f16758750328dda3699b27a44b6217#diff-27f791a113d9748b525128d595f3cb8a633a468c1df16c418f5dfd5243869d95 you can see the download url lost a large portion of itself: 

`https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_18129-20030.exe#/dl.7z_` -> `https://download.microsoft.com/download/#/dl.7z_`.

Also in the past day it's been on version `23.4.0`, `v1.2024.9.14`, `6.3.3`, `8.7.4`, `1.5.5.0` and `23.4.0` so something looks to be wrong.
