### ISSUE TITLE
[Request] upgrade bluestacks-np to major version 5. 

### ISSUE THREAD

**Issue by Lutra-Fs** [ScoopInstaller/Nonportable#46]
### Criteria

For a package to be acceptable in the Nonportable bucket, it should be:

- [x] a reasonably well-known and widely used application
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version

### Information

**Name:**  BlueStacks 5

**Description:**Android Emulator

**Homepage:** https://www.bluestacks.com/

**Download link(s):** https://support.bluestacks.com/hc/en-us/articles/4402611273485-BlueStacks-5-offline-installer

**Some indication of popularity/repute:** nxt version of current Bluestacks manifest in the bucket, see https://support.bluestacks.com/hc/en-us/articles/4415222167949-Why-should-I-move-to-BlueStacks-5-
Also in this major version, the installer can handle with or without hyper-v
Note: Windows Insider may face some issues staring the app, similar as 4

Rename the cur manifest to `bluestacks4-np` and `bluestacks4-hyperv-np`

**Comment by issaclin32** [comment]
I think we should add *BlueStacks 5* as `bluestacks-np`, and **rename** the current package to `bluestacks4-np`.

Keep the same rule as the *Main* and *Extras* bucket.

**Comment by issaclin32** [comment]
I found [this page](https://support.bluestacks.com/hc/en-us/articles/4402611273485-BlueStacks-5-offline-installer), which has the link to the offline installer and is being constantly updated (see [snapshot from archive.org](https://web.archive.org/web/20220604123914/https://support.bluestacks.com/hc/en-us/articles/4402611273485-BlueStacks-5-offline-installer) for example)

The problem is, the page cannot be loaded with `Invoke-WebRequest` or `Invoke-RestMethod` (error 403: Forbidden)
